servicemonitor:
  enabled: true

resources:
  enabled: false

config:
  upf:
    sriov:
      enabled: false
    hugepage:
      enabled: false
    cniPlugin: macvlan
    access:
      ip: "10.5.1.2/24"
      gateway: "10.5.1.1"
      iface: eno12399   #@@??
    core:
      ip: "10.5.2.2/24"
      gateway: "10.5.2.1"
      iface: eno12399   #@@??
    enb:
      subnet: "10.5.3.0/24"
    cfgFiles:
      upf.json:
        mode: af_packet
        cpiface:
          enable_ue_ip_alloc: true
          ue_ip_pool: "10.250.4.0/24"
        qci_qos_config:
          - qci: 0 # Fallback QCI
            cbs: 50000
            ebs: 50000
            pbs: 50000
            burst_duration_ms: 100
            priority: 7
