kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: roc
  namespace: fleet-local
spec:
  repo: https://github.com/mahousu/aether-configs
  branch: main
  paths:
    - sys/atomix-controller
    - sys/atomix-raft-storage
    - sys/onos-operator
    - app/roc
  targets:
    - clusterSelector: {}
