kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: sdfabric
  namespace: fleet-local
spec:
  repo: https://github.com/mahousu/aether-configs
  branch: main
  paths:
    - app/onos
    - app/stratum
    - app/pfcp-agent
  targets:
    - clusterSelector: {}
