apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lb
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 10.5.0.1
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: rke2-ingress-nginx
    app.kubernetes.io/name: rke2-ingress-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
